const ADD_TO_CART = 'ADD_TO_CART';
const INCREASE_ITEM = 'INCREASE_ITEM';
const DECREASE_ITEM = 'DECREASE_ITEM';
const DEL_ITEM = 'DEL_ITEM';
const CHANGE_FORM = 'CHANGE_FORM';
const SUBMIT_FORM = 'SUBMIT_FORM';
const BUY = 'BUY';
const LOG_IN = 'LOG_IN';
const REGISTER = 'REGISTER';
const GET_PRODUCT = 'GET_PRODUCT';
const GET_PRODUCT_APRI = 'GET_PRODUCT_APRI';
const GET_USER_PROFILE = 'GET_USER_PROFILE';
const LOG_OUT = 'LOG_OUT';
const PRODUCT_MANAGE = 'PRODUCT_MANAGE';
const USER_MANAGE = 'USER_MANAGE';
const ORDER_MANAGE = 'ORDER_MANAGE';
const GET_CATEGORY = 'GET_CATEGORY';
export { ADD_TO_CART, INCREASE_ITEM, 
    DECREASE_ITEM, DEL_ITEM, CHANGE_FORM, 
    SUBMIT_FORM, BUY, LOG_IN, REGISTER, 
    GET_USER_PROFILE,
    GET_PRODUCT, LOG_OUT, ORDER_MANAGE , USER_MANAGE, PRODUCT_MANAGE, GET_PRODUCT_APRI,
    GET_CATEGORY}