const ADD_TO_CART = 'ADD_TO_CART';
const INCREASE_ITEM = 'INCREASE_ITEM';
const DECREASE_ITEM = 'DECREASE_ITEM';
const DEL_ITEM = 'DEL_ITEM';
const CHANGE_FORM = 'CHANGE_FORM';
const SUBMIT_FORM = 'SUBMIT_FORM';
const BUY = 'BUY';
const LOG_IN = 'LOG_IN';
const REGISTER = 'REGISTER';
const GET_PRODUCT = 'GET_PRODUCT';
export { ADD_TO_CART, INCREASE_ITEM, DECREASE_ITEM, DEL_ITEM, CHANGE_FORM, SUBMIT_FORM, BUY, LOG_IN, REGISTER, GET_PRODUCT }